openapi: 3.0.0
info:
  title: Saison API
  version: 1.0.0
tags:
  - name: Saisons
    description: Endpoints pour gérer les saisons
paths:
  /updateSeuils/{saisonId}:
  patch:
    summary: Mettre à jour les seuils de nomination et d'élimination d'une saison
    description: Mettre à jour les seuils de nomination et d'élimination d'une saison par son ID.
    tags:
      - Saisons
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: saisonId
        required: true
        description: ID de la saison à mettre à jour.
        schema:
          type: string
      - in: body
        name: body
        required: true
        description: Objet JSON contenant les seuils de nomination et d'élimination à mettre à jour.
        schema:
          type: object
          properties:
            seuilNomination:
              type: number
              description: Seuil de nomination à mettre à jour.
            seuilElimination:
              type: number
              description: Seuil d'élimination à mettre à jour.
    responses:
      "200":
        description: Seuils mis à jour avec succès.
        content:
          application/json:
            example:
              message: "Seuils (seuilNomination, seuilElimination) updated successfully"
      "404":
        description: Saison non trouvée.
        content:
          application/json:
            example:
              message: "Saison not found"
      "500":
        description: Erreur lors de la mise à jour des seuils.
        content:
          application/json:
            example:
              message: "Error updating seuils"
/getListeNominationSaisonActuelle/{saisonId}:
  get:
    summary: Obtenir la liste des choristes nominés pour la saison actuelle
    description: Obtenir la liste des choristes nominés pour la saison actuelle en fonction du seuil de nomination.
    tags:
      - Saisons
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: saisonId
        required: true
        description: ID de la saison pour laquelle obtenir la liste de nominations.
        schema:
          type: string
    responses:
      "200":
        description: Liste des choristes nominés obtenue avec succès.
        content:
          application/json:
            example:
              seuilNomination: 5
              nominatedChoristes:
                - _id: "6585f64b5e6eaf2afafc0482"
                  nom: "ahmed"
                  prenom: "ahmed"
                  email: "ahmed@example.com"
                  numero_téléphone: "123456789"
                - _id: "6585f64b5e6eaf2afafc0484"
                  nom: "khaled"
                  prenom: "khaled"
                  email: "khaled@example.com"
                  numero_téléphone: "987654321"
      "404":
        description: Saison non trouvée.
        content:
          application/json:
            example:
              message: "Saison not found"
      "500":
        description: Erreur lors de la récupération des choristes nominés.
        content:
          application/json:
            example:
              message: "Error fetching nominated choristers"
/getListeEliminationSaisonActuelle/{saisonId}:
  get:
    summary: Obtenir la liste des choristes éliminés pour la saison actuelle
    description: Obtenir la liste des choristes éliminés pour la saison actuelle en fonction du seuil d'élimination.
    tags:
      - Saisons
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: saisonId
        required: true
        description: ID de la saison pour laquelle obtenir la liste des éliminations.
        schema:
          type: string
    responses:
      "200":
        description: Liste des choristes éliminés obtenue avec succès.
        content:
          application/json:
            example:
              seuilElimination: 10
              nombre_choristes_elimines: 3
              eliminatedChoristes:
                - _id: "6585f64b5e6eaf2afafc04aa"
                  nom: "nadia"
                  prenom: "nadia"
                  email: "nadia@example.com"
                  numero_téléphone: "123456789"
                - _id: "6585f64b5e6eaf2afafc0477"
                  nom: "ghalia"
                  prenom: "ghalia"
                  email: "ghalia@example.com"
                  numero_téléphone: "987654321"
                - _id: "6585f64b5e6eaf2afafc04ee"
                  nom: "hadil"
                  prenom: "hadil"
                  email: "hadil@example.com"
                  numero_téléphone: "555555555"
      "404":
        description: Saison non trouvée.
        content:
          application/json:
            example:
              message: "Saison not found"
      "500":
        description: Erreur lors de la récupération des choristes éliminés.
        content:
          application/json:
            example:
              message: "Error fetching eliminated choristers"
/updateDureeElimination/{saisonId}:
  patch:
    summary: Mettre à jour la durée d'élimination pour une saison
    description: Mettre à jour la durée d'élimination pour une saison spécifiée.
    tags:
      - Saisons
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: saisonId
        required: true
        description: ID de la saison à mettre à jour.
        schema:
          type: string
      - in: body
        name: body
        required: true
        description: Objet JSON contenant la nouvelle durée d'élimination.
        schema:
          type: object
          properties:
            dureeElimination:
              type: number
              minimum: 1
              description: Nouvelle durée d'élimination en jours.
    responses:
      "200":
        description: La durée d'élimination de la saison a été mise à jour avec succès.
        content:
          application/json:
            example:
              success: true
              data:
                _id: "6585f64b5e6eaf2afafc04tt"
                dureeElimination: 14
                dateDebut: "2024-01-01T00:00:00.000Z"
                dateFin: "2024-01-15T00:00:00.000Z"
              message: "Duree elimination updated successfully"
      "404":
        description: Saison non trouvée.
        content:
          application/json:
            example:
              message: "Saison not found"
      "500":
        description: Erreur lors de la mise à jour de la durée d'élimination.
        content:
          application/json:
            example:
              success: false
              error: "Error updating duree elimination"

/createsaison:
  post:
    tags:
      - Saisons
    summary: Create a new saison
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SaisonRequest"
    responses:
      "201":
        description: Season created successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Saison"
      "500":
        description: Internal Server Error
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  enum: [false]
                message:
                  type: string

/components:
  schemas:
    SaisonRequest:
      type: object
      properties:
        nom:
          type: string
        dateDebut:
          type: string
          format: date
        dateFin:
          type: string
          format: date
        seuil_absence:
          type: string
        archive:
          type: boolean
    Saison:
      type: object
      properties:
        _id:
          type: string
        nom:
          type: string
        dateDebut:
          type: string
          format: date
        dateFin:
          type: string
          format: date
        seuil_absence:
          type: string
        archive:
          type: boolean
